# Generated by Django 5.1 on 2024-10-21 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_caracteristica_tipo_caracteristica_alto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='caracteristicas',
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.caracteristica'),
        ),
    ]
